services:
  app:
    build: .
    ports:
      - ${PORT:-3000}:8000
    volumes:
      - .:/home/app/php
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db:/var/lib/postgresql/data
      - ./.docker/db:/docker-entrypoint-initdb.d/

volumes:
  db:
    driver: local